name: Debug Repository Structure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  explore:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Explore repository structure
      run: |
        echo "Current directory:"
        pwd
        echo "\nFiles in current directory:"
        ls -la
        echo "\nSearch for pom.xml files:"
        find . -name "pom.xml" -type f
        echo "\nRepository structure (up to 3 levels):"
        find . -type f -maxdepth 3 | sort
        
    # Commenté jusqu'à ce que nous trouvions le fichier pom.xml
    # - name: Set up JDK 21
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '21'
    #     distribution: 'temurin'
    #     
    # - name: Build with Maven
    #   run: mvn -B clean package
